### ISSUE TITLE
Marklar editor is shown only in description while editing Wiki page on Moodle 3.4

### ISSUE THREAD

**Issue by N0rbert** [mudrd8mz/moodle-editor_marklar#13]
I have installed Moodle 3.4, created new course and added wiki to it.
I disabled other text editors, installed Marklar (so it is default editor).

In wiki Marklar editor is shown in *Edit settings*, *General* -> *Description* (url is course/modedit.php?update=2&return=1).

But Marklar is not shown while editing page body in *Edit* -> *Editing this page*, *HTML format* (url is mod/wiki/edit.php?pageid=1) even if I set *Markdown format* in drop-down under text-area).

Is it bug of Moodle or of Marklar?

**Comment by mudrd8mz** [comment]
Please go to your user Preferences > Miscellaneous > Marklar editor preferences 

Make sure that HTML format is also selected.

Then you should be able to edit Wiki pages with Marklar, too.

**Comment by mudrd8mz** [comment]
![image](https://user-images.githubusercontent.com/85831/36329697-33c391e0-1367-11e8-843f-a4f5334254ef.png)

**Comment by N0rbert** [comment]
Am I understand correctly, that after this setting I can use Markdown in *HTML format field*? Or this setting will enable editor but only for HTML syntax?

**Comment by mudrd8mz** [comment]
That setting affects which editor will be used when you are editing any rich text field in Moodle, depending on the selected format of that field.

**Comment by N0rbert** [comment]
OK, understood. Thank you!
