### ISSUE TITLE
Any ideas to make line break with "\"?

### ISSUE THREAD

**Issue by vladyslav2** [mudrd8mz/moodle-editor_marklar#14]
Hello
I'm really thank you for you plugin

Do you have any ideas with ```\``` working as a line break?
Please check out this post https://gist.github.com/shaunlebron/746476e6e7a4d698b373#gistcomment-2271765

I believe its features we really need cause two spaces are not visible

Thank you

**Comment by mudrd8mz** [comment]
Please note, it is not Marklar's duty to actually format the Markdown text. That is Moodle core feature. I don't know if it supports line breaks via backslashes (and I don't think it is even part of the original syntax https://daringfireball.net/projects/markdown/syntax that Moodle uses).

Explicit `<br>` should work.

**Comment by vladyslav2** [comment]
Thank you @mudrd8mz 
> I don't know if it supports line breaks via backslashes 
It does not

> Explicit <br> should work.
Takes much longer to type that `\`

>  That is Moodle core feature.
Will try to connect with them but this would be much difficult, I hopped Marklar does this
