### ISSUE TITLE
format_text() nocache option deprecated

### ISSUE THREAD

**Issue by vmdef** [mudrd8mz/moodle-editor_marklar#27]
The use of the [nocache](https://github.com/mudrd8mz/moodle-editor_marklar/blob/288d316bd4ec7018367208c2487d8006a2c421ba/classes/external/get_preview.php#L69) option in the  **format_text()** function was deprecated in Moodle 2.3 (MDL-34347).

In Moodle 4.4, this option triggers a debugging output that causes PHPUnit tests to fail.

**Comment by mudrd8mz** [comment]
Oh good catch Victor! Thanks a lot!

**Comment by mudrd8mz** [comment]
Fixed in 1.0.1 - f0f15632b10aafb57697519349275214482d63bc
