### ISSUE TITLE
No link for 'Contribute translation for {your language}' in Moodle plugins page for marklar

### ISSUE THREAD

**Issue by germanvaleroelizondo** [mudrd8mz/moodle-editor_marklar#6]
Hi David, 

I found it odd that the page at https://moodle.org/plugins/editor_marklar , in the section of 'Useful links' does not show a ling for 'Contribute translation for {your language}'.

**Comment by mudrd8mz** [comment]
Hi German. Well spotted! There is a little bug in the code that affects all plugins submitted by the plugins directory administrators, including myself.

**Comment by germanvaleroelizondo** [comment]
I hope you can fix this quickly, so that it will be easier  to translate all your great plugins :)
