### ISSUE TITLE
Does not work and look good if used as a field in database activity

### ISSUE THREAD

**Issue by wildgirl** [mudrd8mz/moodle-editor_marklar#7]
In a database activity, the text area field is narrow (narrower than defined in the field setting) e.g. https://moodle.org/mod/data/edit.php?d=54 This bug only affects you if you're using the marklar text editor.

**Comment by mudrd8mz** [comment]
Thanks Helen. I think for now I will do the same as I did in admin configuration (for HTML editor admin fields) - that is effectively disable Marklar there. On contrary to TinyMCE or Atto that effectively replace the original textarea field, the Marklar editor tries to enhance it instead. It works well if the editor is part of a moodle form. But it fails elsewhere (not for example that the Preview button does not work in this case, too).

The proper solution for a future version would be to rethink the way how the Marklar is initialised in the page, and make sure it can be safely used anywhere, even out of the moodle forms.

**Comment by wildgirl** [comment]
I'm not sure it is necessary to disable Marklar there, as you have the option to resize the text area and make it wider. It's only a tiny bug, and when you're used to using Marklar it is distressing to have the HTML editor forced on you.

**Comment by mudrd8mz** [comment]
I think I have a fix for this. There is no way to provide the Preview feature in the Database activity (due to way how it has text format selector implemented) but it should no longer make the Marklar that narrow.

**Comment by mudrd8mz** [comment]
Should be fixed in version 0.5.0

**Comment by wildgirl** [comment]
Thanks David for the fix. It looks fine on moodle.org.
